#!/bin/bash

set -e

CATALINA_HOME=/usr/share/agwebapps

TEMP_STAGING_DIR='/tmp/codedeploy-deployment-staging-area'

rm -rfv $CATALINA_HOME/

cp -rf $TEMP_STAGING_DIR/target $CATALINA_HOME/

# Create the service init.d script
cat > /etc/init.d/springpet <<'EOF'
CATALINA_HOME=/usr/share/agwebapps

SERVICE_NAME=springpet
PATH_TO_JAR=$CATALINA_HOME/spring-petclinic-2.3.1.BUILD-SNAPSHOT.jar 
PID_PATH_NAME=/tmp/springpet-pid
case $1 in 
start)
       echo "Starting $SERVICE_NAME ..."
  if [ ! -f $PID_PATH_NAME ]; then 
       nohup java -jar $PATH_TO_JAR /tmp 2>> /dev/null >>/dev/null &      
                   echo $! > $PID_PATH_NAME
       echo "$SERVICE_NAME started ..."
  else
       echo "$SERVICE_NAME is already running ..."
  fi
;;
stop)
  if [ -f $PID_PATH_NAME ]; then
         PID=$(cat $PID_PATH_NAME);
         echo "$SERVICE_NAME stoping ..." 
         kill $PID;         
         echo "$SERVICE_NAME stopped ..." 
         rm $PID_PATH_NAME       
  else          
         echo "$SERVICE_NAME is not running ..."   
  fi    
;;    
restart)  
  if [ -f $PID_PATH_NAME ]; then 
      PID=$(cat $PID_PATH_NAME);    
      echo "$SERVICE_NAME stopping ..."; 
      kill $PID;           
      echo "$SERVICE_NAME stopped ...";  
      rm $PID_PATH_NAME     
      echo "$SERVICE_NAME starting ..."  
      nohup java -jar $PATH_TO_JAR /tmp 2>> /dev/null >> /dev/null &            
      echo $! > $PID_PATH_NAME  
      echo "$SERVICE_NAME started ..."    
  else           
      echo "$SERVICE_NAME is not running ..."    
     fi     ;;
 esac
EOF

# Change permission mode for the service script
chmod 755 /etc/init.d/springpet
