#!/bin/bash

#stop if something fails
set -e

CATALINA_HOME=/usr/share/agwebapps
TEMP_STAGING_DIR='/tmp/codedeploy-deployment-staging-area'
#TOMCAT_VERSION=7.0.106

# Tar file name
#TOMCAT7_CORE_TAR_FILENAME="apache-tomcat-$TOMCAT_VERSION.tar.gz"
# Download URL for Tomcat7 cor
#TOMCAT7_CORE_DOWNLOAD_URL="https://downloads.apache.org/tomcat/tomcat-7/v$TOMCAT_VERSION/bin/$TOMCAT7_CORE_TAR_FILENAME"
# The top-level directory after unpacking the tar file
#TOMCAT7_CORE_UNPACKED_DIRNAME="apache-tomcat-$TOMCAT_VERSION"


# Check whether there exists a valid instance
# of Tomcat7 installed at the specified directory
# [[ -d $CATALINA_HOME ]] && { service tomcat7 status; } && {
#     echo "Tomcat7 is already installed at $CATALINA_HOME. Skip reinstalling it."
#     exit 0
# }

# Clear install directory --- Not necessary since using maven
if [ -d $CATALINA_HOME ]; then
    rm -rf $CATALINA_HOME
    echo "AG - $CATALINA_HOME DELETED "
fi
mkdir -p $CATALINA_HOME
echo "AG - $CATALINA_HOME CREATED "

# Clear Stage Directory
# if [ -d $TEMP_STAGING_DIR ]; then
#     rm -rf $TEMP_STAGING_DIR
#     echo "AG - STAGE TEMP DIR: $TEMP_STAGING_DIR DELETED "
# fi
# mkdir -p $TEMP_STAGING_DIR
# echo "AG - STAGE TEMP DIR: $TEMP_STAGING_DIR CREATED "
# rm -f /etc/init.d/springpet

#rm -rfv $CATALINA_HOME/

# # Download the latest Tomcat7 version
# cd /tmp
# { which wget; } || { yum install wget; }
# wget $TOMCAT7_CORE_DOWNLOAD_URL
# if [[ -d /tmp/$TOMCAT7_CORE_UNPACKED_DIRNAME ]]; then
#     rm -rf /tmp/$TOMCAT7_CORE_UNPACKED_DIRNAME
# fi
# tar xzf $TOMCAT7_CORE_TAR_FILENAME

# Copy over to the CATALINA_HOME
echo "AG - TEMP_STAGING_DIR: $TEMP_STAGING_DIR"
echo "AG - CATALINA_HOME: $CATALINA_HOME"
cp -R $TEMP_STAGING_DIR/* $CATALINA_HOME
echo "AG - COPIED FILES FROM : $TEMP_STAGING_DIR TO $CATALINA_HOME"
# Install Java if not yet installed
{ which java; } || { yum install java -y; }

# cd $CATALINA_HOME
# ./mvnw dependency:go-offline
# # Create the service init.d script
# cat > /etc/init.d/tomcat7 <<'EOF'
# #!/bin/bash
# # description: Tomcat7 Start Stop Restart
# # processname: tomcat7
# PATH=$JAVA_HOME/bin:$PATH
# export PATH
# CATALINA_HOME='/usr/share/tomcat7-codedeploy'

# case $1 in
# start)
# sh $CATALINA_HOME/bin/startup.sh
# ;;
# stop)
# sh $CATALINA_HOME/bin/shutdown.sh
# ;;
# restart)
# sh $CATALINA_HOME/bin/shutdown.sh
# sh $CATALINA_HOME/bin/startup.sh
# ;;
# esac
# exit 0
# EOF

# # Change permission mode for the service script
# chmod 755 /etc/init.d/tomcat7
