#!/bin/bash

set -e -m
CATALINA_HOME=/usr/share/agwebapps
#service springpet start

echo "AG - Start Application"
echo "AG - Changing to CATALINA_HOME: $CATALINA_HOME"
cd $CATALINA_HOME
./mvnw spring-boot:start

#java -jar spring-petclinic-2.3.1.BUILD-SNAPSHOT.jar & echo $! > ./pid.file & bg

# Copy the WAR file to the webapps directory
# cp $WAR_STAGED_LOCATION $CATALINA_HOME/webapps/$CONTEXT_PATH.war

# # Configure the Tomcat server HTTP connector
# { which xsltproc; } || { yum install xsltproc; } || { apt-get install xsltproc; }
# cp $CATALINA_HOME/conf/server.xml $CATALINA_HOME/conf/server.xml.bak
# xsltproc $HTTP_PORT_CONFIG_XSL_LOCATION $CATALINA_HOME/conf/server.xml.bak > $CATALINA_HOME/conf/server.xml

# service tomcat7 start