#!/bin/bash

# PID_PATH_NAME=/tmp/springpet-pid

# if [ -f $PID_PATH_NAME ]; then
#      PID=$(cat $PID_PATH_NAME);
#      echo "$SERVICE_NAME stoping ..." 
#      kill $PID;         
#      echo "$SERVICE_NAME stopped ..." 
#      rm $PID_PATH_NAME       
# else          
#      echo "$SERVICE_NAME is not running ..."
# fi

ps -aux | grep "[s]pring-boot" | awk '{print $2}' | \
while read i;
     do kill -9 $i;
done